# Generated by Django 5.0.3 on 2024-03-12 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64, unique=True)),
                ('series', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('audio', 'Speakers'), ('battery', 'Battery'), ('camera', 'Webcam'), ('display', 'Display'), ('keyboard', 'Keyboard'), ('memory', 'Memory RAM'), ('motherboard', 'Motherboard'), ('network', 'Network card'), ('storage', 'Hard drive'), ('touch', 'Touchpad')], max_length=16)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaptopParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thinkpart.laptop')),
                ('alternative', models.ManyToManyField(related_name='alternative_part', to='thinkpart.part')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_part', to='thinkpart.part')),
            ],
        ),
        migrations.CreateModel(
            name='UserLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased', models.DateTimeField(auto_now_add=True)),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thinkpart.laptop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReplacedParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('part_current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thinkpart.part')),
                ('part_old', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thinkpart.laptopparts')),
                ('user_laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thinkpart.userlaptop')),
            ],
        ),
    ]
