# Generated by Django 5.0.3 on 2024-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='manufacturer',
            field=models.CharField(default='Lenovo', max_length=255),
            preserve_default=False,
        ),
    ]
