# Generated by Django 5.0.3 on 2024-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpart', '0002_part_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
