# Generated by Django 5.0.3 on 2024-03-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpart', '0004_alter_laptopparts_alternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlaptop',
            name='purchased',
            field=models.DateField(auto_now_add=True),
        ),
    ]
