# Generated by Django 5.0.3 on 2024-03-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpart', '0005_alter_userlaptop_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreplacedparts',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userreplacedparts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userreplacedparts',
            name='part_current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_part_current', to='thinkpart.part'),
        ),
        migrations.AlterField(
            model_name='userreplacedparts',
            name='part_old',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replaced_part_old', to='thinkpart.part'),
        ),
    ]
