# Generated by Django 5.0.3 on 2024-03-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpart', '0006_alter_userreplacedparts_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaptopParts',
            new_name='LaptopPart',
        ),
        migrations.AlterField(
            model_name='userreplacedparts',
            name='part_old',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replaced_part_original', to='thinkpart.part'),
            preserve_default=False,
        ),
    ]
