# Generated by Django 5.0.3 on 2024-03-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpart', '0007_rename_laptopparts_laptoppart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReplacedParts',
            new_name='UserReplacedPart',
        ),
        migrations.AlterField(
            model_name='userreplacedpart',
            name='part_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_part_original', to='thinkpart.laptoppart'),
        ),
    ]
