# Generated by Django 5.0.3 on 2024-03-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpart', '0008_rename_userreplacedparts_userreplacedpart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreplacedpart',
            old_name='part_old',
            new_name='part_original',
        ),
    ]
