# Generated by Django 5.0.3 on 2024-03-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thinkpart', '0011_alter_laptop_options_alter_userlaptop_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreplacedpart',
            options={},
        ),
    ]
